// <auto-generated />
using HCTKanban.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCTKanban.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250102100809_AppUsers")]
    partial class AppUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HCTKanban.Data.ApplicationUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HCTKanban.Models.BirdBox", b =>
                {
                    b.Property<int>("BirdBoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BirdBoxId"));

                    b.Property<int>("BirdBoxStatusId")
                        .HasColumnType("int");

                    b.Property<int>("BirdBoxTypeId")
                        .HasColumnType("int");

                    b.Property<string>("JSidentifier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BirdBoxId");

                    b.HasIndex("BirdBoxTypeId");

                    b.ToTable("BirdBox");
                });

            modelBuilder.Entity("HCTKanban.Models.BirdBoxType", b =>
                {
                    b.Property<int>("BirdBoxTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BirdBoxTypeId"));

                    b.Property<string>("BirdBoxName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BirdBoxTypeId");

                    b.ToTable("BirdBoxType");
                });

            modelBuilder.Entity("HCTKanban.Models.Locations", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("HCTKanban.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StatusId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("HCTKanban.Models.BirdBox", b =>
                {
                    b.HasOne("HCTKanban.Models.BirdBoxType", "BirdBoxType")
                        .WithMany("BirdBoxes")
                        .HasForeignKey("BirdBoxTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirdBoxType");
                });

            modelBuilder.Entity("HCTKanban.Models.BirdBoxType", b =>
                {
                    b.Navigation("BirdBoxes");
                });
#pragma warning restore 612, 618
        }
    }
}
